# Generated by Django 2.1.5 on 2019-01-18 07:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_index=True, max_length=255, validators=[django.core.validators.MinLengthValidator(11)]),
        ),
    ]
